import { chromium } from "playwright";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 420, height: 950 } });
const p = await ctx.newPage();
p.on("dialog", async d => { await d.accept("test-pass-123"); });
const rpc=[]; const csp=[];
p.on("request", r => { const u=r.url(); if (u.includes("helius")) rpc.push("HELIUS"); });
p.on("console", m => { if (/violates the following Content Security|Refused to connect/i.test(m.text())) csp.push(m.text().slice(0,80)); });
await p.goto("http://localhost:3000/app", { waitUntil:"networkidle" }).catch(()=>{});
await p.waitForTimeout(1500);
await p.locator("text=Continue with a demo account").click().catch(()=>{});
await p.waitForTimeout(2500);
await p.getByRole("button",{name:/^Grow/i}).first().click().catch(()=>{});
await p.waitForTimeout(1000);
await p.getByRole("button",{name:/Create an account/i}).first().click().catch(()=>{});
await p.waitForTimeout(6000);
await p.getByRole("button",{name:/Get test USDC/i}).first().click().catch(()=>{});
await p.waitForTimeout(10000);
const body = await p.evaluate(()=>document.body.innerText);
const walletLine = (body.split("\n").find(l=>/Wallet USDC/i.test(l)) || body.match(/Wallet USDC[\s\S]{0,20}/)?.[0] || "").slice(0,40);
// grab the two balance numbers near the tiles
const nums = await p.evaluate(()=>{
  const t=[...document.querySelectorAll("div")];
  const w=t.find(e=>e.textContent?.trim()==="Wallet USDC")?.nextElementSibling?.textContent;
  const v=t.find(e=>e.textContent?.trim()==="In your vault")?.nextElementSibling?.textContent;
  return {wallet:w, vault:v};
});
console.log("Helius RPC calls from browser:", rpc.length);
console.log("CSP blocks:", csp.length?csp.slice(0,2):"none ✓");
console.log("balances:", JSON.stringify(nums));
await b.close();
